 server:
  port: 8200
 spring:
   application:
     name: microservice-hystrix-turbine
 eureka:
  client:
    serviceUrl:
      defaultZone: http://user:123456@localhost:8079/eureka
  instance:
    prefer-ip-address: true
 turbine:
   aggregator:
     clusterConfig: default
   appConfig: microservice-consumer-movie-ribbon-hystrix,microservice-consumer-movice-feign-with-hystrix
   clusterNameExpression: "'default'"