 management: # spring-boot-starter-acturator
   port: 8201
 server:
  port: 8200
 spring:
   application:
     name: microservice-hystrix-turbine2
 eureka:
  client:
    serviceUrl:
      defaultZone: http://user:123456@localhost:8079/eureka
  instance:
    prefer-ip-address: true
 turbine:
   aggregator:
     clusterConfig: MICROSERVICE-CONSUMER-MOVIE-RIBBON-HYSTRIX2
   appConfig: microservice-consumer-movie-ribbon-hystrix2
   #clusterNameExpression: "'default'"
 turbine.instanceUrlSuffix.MICROSERVICE-CONSUMER-MOVIE-RIBBON-HYSTRIX2: /ribbon/hystrix.stream
 logging:
   level:
     root: INFO
     com.netflix.turbine.monitor: DEBUG